const petstoreVersions = require('./docs/apps/nest-app/microservice-14-pet/petstore_versioned/versions.json');
const {
  versionSelector,
  versionCrumb,
} = require('docusaurus-plugin-openapi-docs/lib/sidebars/utils');

const sidebars = {
  petstore: [
    /*
    'introduction',
    'about',
    'resume',
    'timeline',
    {
      type: 'category',
      label: 'Packages',
      link: {
        type: 'generated-index',
        title: 'Packages API',
        description: 'Packages',
        slug: '/category/packages-api',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Universal Components Library',
          link: {
            type: 'doc',
            id: 'packages/universal-components-library/introduction',
          },
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'DefaultButton',
              link: {
                type: 'doc',
                id: 'packages/universal-components-library/DefaultButton/DefaultButton',
              },
              collapsed: true,
              items: [
                'packages/universal-components-library/DefaultButton/DefaultButton',
              ],
            },
            {
              type: 'category',
              label: 'DefaultLongButton',
              link: {
                type: 'doc',
                id: 'packages/universal-components-library/DefaultLongButton/DefaultLongButton',
              },
              collapsed: true,
              items: [
                'packages/universal-components-library/DefaultLongButton/DefaultLongButton',
              ],
            },
            {
              type: 'category',
              label: 'Label',
              link: {
                type: 'doc',
                id: 'packages/universal-components-library/Label/Label',
              },
              collapsed: true,
              items: ['packages/universal-components-library/Label/Label'],
            },
            {
              type: 'category',
              label: 'Input',
              link: {
                type: 'doc',
                id: 'packages/universal-components-library/Input/Input',
              },
              collapsed: true,
              items: ['packages/universal-components-library/Input/Input'],
            },
          ],
        },
      ],
    },
    */
    'introduction',
    'about',
    'resume',
    'timeline',
    {
      type: 'category',
      label: 'Packages',
      link: {
        type: 'generated-index',
        title: 'Packages API',
        description: 'Applications',
        slug: '/category/packages-api',
      },
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Universal Components Library',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'packages',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Applications',
      link: {
        type: 'generated-index',
        title: 'Applications API',
        description: 'Applications',
        slug: '/category/applications-api',
      },
      collapsed: true,
      items: [
        /*
        {
          type: 'category',
          label: 'Customization',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'customization',
            },
          ],
        },
        */
        {
          type: 'category',
          label: 'Nest Application',
          link: {
            type: 'doc',
            id: 'apps/nest-app/introduction',
          },
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Microservice Pets',
              link: {
                type: 'generated-index',
                title: 'Pets API',
                description:
                  'This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.',
                slug: '/category/petstore-api',
              },
              items: require('./docs/apps/nest-app/microservice-14-pet/petstore/sidebar.js'),
            },
            {
              type: 'category',
              label: 'Microservice Orders',
              link: {
                type: 'generated-index',
                title: 'Order API',
                slug: '/category/order-api',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'apps/nest-app/microservice-11-order', // '.' means the current docs folder
                },
              ],
            },
            {
              type: 'category',
              label: 'Microservice Payments',
              link: {
                type: 'generated-index',
                title: 'Payment API',
                slug: '/category/payment-api',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'apps/nest-app/microservice-12-payment', // '.' means the current docs folder
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  'petstore-2.0.0': [
    {
      type: 'html',
      defaultStyle: true,
      value: versionSelector(petstoreVersions),
      className: 'version-button',
    },
    {
      type: 'html',
      defaultStyle: true,
      value: versionCrumb(`v2.0.0`),
    },
    {
      type: 'category',
      label: 'Petstore',
      link: {
        type: 'generated-index',
        title: 'Petstore API (latest)',
        description:
          'This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.',
        slug: '/category/petstore-versioned-api',
      },
      items: require('./docs/apps/nest-app/microservice-14-pet/petstore_versioned/sidebar.js'),
    },
  ],

  'petstore-1.0.0': [
    {
      type: 'html',
      defaultStyle: true,
      value: versionSelector(petstoreVersions),
      className: 'version-button',
    },
    {
      type: 'html',
      defaultStyle: true,
      value: versionCrumb(`v1.0.0`),
    },
    {
      type: 'category',
      label: 'Petstore',
      link: {
        type: 'generated-index',
        title: 'Petstore API (v1.0.0)',
        description:
          'This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.',
        slug: '/category/petstore-api-1.0.0',
      },
      items: require('./docs/apps/nest-app/microservice-14-pet/petstore_versioned/1.0.0/sidebar.js'),
    },
  ],
};

module.exports = sidebars;
