module.exports = {
  tutorialSidebar: [
    'introduction',
    {
      type: "autogenerated",
      dirName: "."
    }
  ],
  api: [
    {
      type: "autogenerated",
      dirName: "api"
    }
  ]
};
