export const CASHIFY = 'CASHIFY_TOKEN';
export const CASHIFY_OPTIONS = 'CASHIFY_OPTIONS_TOKEN';

export const HASHTABLE = 'HASHTABLE_TOKEN';
export const HASHTABLE_OPTIONS = 'HASHTABLE_OPTIONS_TOKEN';
