FROM alpine as copying
COPY mysql /var/lib/mysql

FROM mysql:8 as gitea-db
ARG ROOT_PASSWORD=gitea
ARG USER=gitea
ARG PASSWORD=gitea
ARG DATABASE=gitea

ENV MYSQL_ROOT_PASSWORD="${ROOT_PASSWORD}"
ENV MYSQL_USER="${USER}"
ENV MYSQL_PASSWORD="${PASSWORD}"
ENV MYSQL_DATABASE="${DATABASE}"

COPY --from=copying /var/lib/mysql /var/lib/mysql
