openapi: 3.0.3
servers:
  - url: https://localhost:2988/
    description: Default server
info:
  title: Payment microservice.
  version: 1.0.0
  description: microservice-12-payment
paths:
  /pay/all:
    get:
      summary: Get all orders
      description: Orders
      responses:
        200:
          description: OK
