name: Docs

on:
  push:
    paths:
      - .github/workflows/apps-docs.yml
      - .github/actions/pnpm-bun-setup/action.yml
      - apps/docs/**
      - packages/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/pnpm-bun-setup
        
      - name: Prepare docs to be build
        run: |
          pnpm run build --filter=docs^...
