name: Website

on:
  push:
    paths:
      - .github/workflows/apps-website.yml
      - .github/actions/pnpm-bun-setup/action.yml
      - apps/website/**
      - packages/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git files setup
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/pnpm-bun-setup
        
      - name: Prepare website to be build
        run: |
          pnpm run build --filter=website^...
          pnpm run typegen --filter=website
