name: CI

on:
  push:
    branches:
      - 'debug'
  pull_request:
  workflow_dispatch:

#permissions:
#  actions: write

jobs:
  multiple:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        cypress:
          - working_directory: services/apps/static-preact-app
          #- working_directory: services/apps/rsc-v8-app
    steps:
      - name: PNPM Init 🛎
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/**/**/pnpm-lock.yaml') }}

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/**/**/pnpm-lock.yaml') }}

      - name: install dependencies and verify Cypress
        working-directory: ${{ matrix.cypress.working_directory }}
        env:
          CI: 1
        run: |
          pnpm install --frozen-lockfile
          npx cypress verify
          npx cypress info
          npx cypress version
          npx cypress version --component package
          npx cypress version --component binary
          npx cypress version --component electron
          npx cypress version --component node
          
      - name: Start the app 📤
        working-directory: ${{ matrix.cypress.working_directory }}
        run: npm start &

      - name: Cypress tests
        working-directory: ${{ matrix.cypress.working_directory }}
        run: npx cypress run 
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

